version: 2.1

workflows:
  build:
    jobs:
      - test
      - publish:
          requires:
            - test
          context:
            - npm
            - github
          filters:
            branches:
              only:
                - main

commands:
  build:
    steps:
      - restore_cache:
          key: yarn-cache-{{ .Branch }}
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: yarn-cache-{{ .Branch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: yarn build

jobs:
  test:
    docker:
      - image: cimg/node:20.8.0
    steps:
      - checkout
      - build
      - run:
          name: Test
          command: yarn test:ci

  publish:
    docker:
      - image: cimg/node:20.8.0
    steps:
      - checkout
      - build
      - run:
          name: Add npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: ./.circleci/publish.sh
